### ISSUE TITLE
Missing the green library badge in modmenu

### ISSUE THREAD

**Issue by nco2k** [jaredlll08/searchables#5]
can you please modify the mod so that it gets properly recognized as a library by modmenu, and therefor doesnt show up by default?

apis like fabric, cloth, yacl etc. have a green library badge in modmenu, and only show up if you toggle the button from "Libraries: Hidden" to "Libraries: Shown". i would appreciate it if yours behaved the same.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/searchables/commit/21f3a559835966f3d7595ac9fee65fb489295829
