### ISSUE TITLE
[Bug] Version not corresponding

### ISSUE THREAD

**Issue by Kiryonn** [jaredlll08/searchables#6]
When downloading the latest version `Fabric-1.20.2-1.0.11` on modrynth, i got a compatibility issue from controlling telling me that i need the version 1.0.2 or higher. That's an issue in itself, but i changed the value in the `fabric.mod.json` of `searchable` of the controlling mod to 1.0.11, only to see the same issue but mentionning that my current version of searchable was 1.0. And after checking it in the `fabric.mod.json` of the `searchable` mod, it indead had `"version": "1.0"` I changed it to 1.0.11 and it worked.

**Comment by jaredlll08** [comment]
Sorry about that, messing around with my build script and made a typo, should be fixed now.
