### ISSUE TITLE
Enabling Searchables while Crafttweaker is on crashes the game

### ISSUE THREAD

**Issue by asoshinsky** [jaredlll08/searchables#7]
The game crashes if both Crafttweaker and Searchables installed. 

Minecraft version 1.16.5
CraftTweaker-1.16.5-7.1.2.526
Searchables-forge-1.16.5-1.0.6
Controlling-7.0.0.30

org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config searchables.forge.mixins.json
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_16 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.6 (ASM10_EXPERIMENTAL))

**Comment by jaredlll08** [comment]
This is unrelated to CraftTweaker.

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/searchables/commit/c5745ea55d2f8b8aa8f0337f09aa106534539f79
